#! /bin/sh

rm -f private_key
terraform -chdir=terraform output -raw private_key > private_key
chmod 400 private_key
ssh -i private_key -p 4444 ubuntu@$(terraform -chdir=terraform output -raw server_ip)
