#! /bin/sh

if ! [ -f "private_key" ]
then
    terraform -chdir=terraform output -raw private_key > private_key
    chmod 400 private_key
fi

ssh -i private_key root@$(terraform -chdir=terraform output -raw server_ip)
