#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /backend/manage.py migrate
python /backend/manage.py collectstatic --noinput
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/backend
