/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * User model w/o password
 * @export
 * @interface PatchedUserDetails
 */
export interface PatchedUserDetails {
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetails
     */
    readonly pk?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof PatchedUserDetails
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetails
     */
    readonly email?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetails
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetails
     */
    lastName?: string;
}

/**
 * Check if a given object implements the PatchedUserDetails interface.
 */
export function instanceOfPatchedUserDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedUserDetailsFromJSON(json: any): PatchedUserDetails {
    return PatchedUserDetailsFromJSONTyped(json, false);
}

export function PatchedUserDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pk': !exists(json, 'pk') ? undefined : json['pk'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
    };
}

export function PatchedUserDetailsToJSON(value?: PatchedUserDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'first_name': value.firstName,
        'last_name': value.lastName,
    };
}

