#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /application/manage.py migrate
python /application/manage.py collectstatic --noinput
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/application
